---
- name: mozilla-nss | {{ task.name }} | Ensure the Git configuration file
  copy:
    dest: '{{ user_git_file }}'
    mode: '0664'
    src: "{{ role_path }}/files/gitconfig_example"
    force: no
    backup: yes
  register: result_git_file

- name: mozilla-nss | {{ task.name }} | Ensure Git configuration
  lineinfile:
    dest: '{{ user_git_file }}'
    state: '{{ item.state }}'
    create: yes
    insertafter: '^\[user\]'
    backup: yes
    line: '{{ item.parameter }} = {{ item.value }}'
  loop: '{{ git_user_config }}'
  when:
    - item.enabled
    - result_git_file is success

...