---
- name: mozilla-nss | {{ task.name }} | Ensure all packages are installed and updated
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop: '{{ packages }}'

# TODO:
# coverity
# rr
...
